### ISSUE TITLE
Convert to `asdf` over homebrew?

### ISSUE THREAD

**Issue by shamshirz** [corvusinsurance/laptop#12]
`asdf` seems to be a rising start for package/version management.
If we got on the same page we could also do a better job about versioning.
For example. At the time of writing, we are on Elixir 1.9 / OTP 22 and Elm 19
With the script, there really isn't any way to know that or maintain it.

**Comment by gmcintire** [comment]
It looks like everything is handled by asdf and not homebrew at this point.
