### ISSUE TITLE
Script does not detect Atom installed, and repeats install

### ISSUE THREAD

**Issue by mtdarby** [corvusinsurance/laptop#3]
Example output from second time running script:

Missing Atom. Installing…
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  129M  100  129M    0     0  18.5M      0  0:00:06  0:00:06 --:--:-- 20.7M
Archive:  /Users/michelledarby/Downloads/atom.zip
replace /Applications/Atom.app/Contents/_CodeSignature/CodeResources? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: /Applications/Atom.app/Contents/_CodeSignature/CodeResources  
replace /Applications/Atom.app/Contents/Frameworks/Atom Helper EH.app/Contents/_CodeSignature/CodeResources? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: /Applications/Atom.app/Contents/Frameworks/Atom Helper EH.app/Contents/_CodeSignature/CodeResources

**Comment by mtdarby** [comment]
I bypassed by removing that section of the script locally and rerunning it.

**Comment by shamshirz** [comment]
Pulled the script out and added more instructions - https://github.com/corvusinsurance/laptop/pull/4
